apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.configName }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.global.commonLabels }}
  labels:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  conf.yml: |
    enableIPv4: {{ .Values.feature.enableIPv4 }}
    enableIPv6: {{ .Values.feature.enableIPv6 }}
