apiVersion: apps/v1
kind: DaemonSet
metadata:
  name:  {{ .Values.templateAgent.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "project.templateAgent.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "project.templateAgent.selectorLabels" . | nindent 6 }}
  {{- with .Values.templateAgent.updateStrategy }}
  updateStrategy:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- if or .Values.templateAgent.podAnnotations .Values.global.commonAnnotations }}
      annotations:
        {{- if .Values.global.commonAnnotations }}
        {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.templateAgent.podAnnotations }}
        {{- include "tplvalues.render" ( dict "value" .Values.templateAgent.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "project.templateAgent.selectorLabels" . | nindent 8 }}
        {{- if .Values.global.commonLabels }}
        {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.templateAgent.podLabels }}
        {{- include "tplvalues.render" ( dict "value" .Values.templateAgent.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.templateAgent.image.imagePullSecrets }}
      imagePullSecrets:
      {{- with .Values.templateAgent.image.imagePullSecrets }}
      {{- toYaml . | trim | nindent 6 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ .Values.templateAgent.name | trunc 63 | trimSuffix "-" }}
      priorityClassName: {{ default "system-node-critical" .Values.templateAgent.priorityClassName }}
      {{- if .Values.templateAgent.hostnetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- else }}
      hostNetwork: false
      dnsPolicy: ClusterFirst
      {{- end }}
      restartPolicy: Always
      {{- with .Values.templateAgent.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.templateAgent.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.templateAgent.affinity }}
      affinity:
      {{- include "tplvalues.render" (dict "value" .Values.templateAgent.affinity "context" $) | nindent 6 }}
      {{- else }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
              # Compatible with Kubernetes 1.12.x and 1.13.x
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
      {{- end }}
      containers:
        - name: {{ .Values.templateAgent.name | trunc 63 | trimSuffix "-" }}
          image: {{ include "project.templateAgent.image" . | quote }}
          imagePullPolicy: {{ .Values.templateAgent.image.pullPolicy }}
          command:
            - {{ .Values.templateAgent.cmdBinName }}
          args:
            - --config-path=/tmp/config-map/conf.yml
          {{- with .Values.templateAgent.extraArgs }}
          {{- toYaml . | trim | nindent 8 }}
          {{- end }}
          {{- if .Values.templateAgent.prometheus.enabled }}
          ports:
            - name: metrics
              containerPort: {{ .Values.templateAgent.prometheus.port }}
              protocol: TCP
          {{- end }}
          {{- if semverCompare ">=1.20-0" .Capabilities.KubeVersion.Version }}
          startupProbe:
            httpGet:
              host: {{ .Values.feature.enableIPv4 | ternary "127.0.0.1" "::1" | quote }}
              path: /v1/runtime/startup
              port: {{ .Values.templateAgent.healthChecking.port }}
              scheme: HTTP
              httpHeaders:
                - name: "checkType"
                  value: "startupProbe"
            failureThreshold: {{ .Values.templateAgent.healthChecking.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.templateAgent.healthChecking.startupProbe.periodSeconds }}
            successThreshold: 1
          {{- end }}
          livenessProbe:
            httpGet:
              host: {{ .Values.feature.enableIPv4 | ternary "127.0.0.1" "::1" | quote }}
              path: /v1/runtime/liveness
              port: {{ .Values.templateAgent.healthChecking.port }}
              scheme: HTTP
              httpHeaders:
                - name: "checkType"
                  value: "livenessProbe"
            initialDelaySeconds: 60
            periodSeconds: {{ .Values.templateAgent.healthChecking.livenessProbe.periodSeconds }}
            successThreshold: 1
            failureThreshold: {{ .Values.templateAgent.healthChecking.livenessProbe.failureThreshold }}
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              host: {{ .Values.feature.enableIPv4 | ternary "127.0.0.1" "::1" | quote }}
              path: /v1/runtime/readiness
              port: {{ .Values.templateAgent.healthChecking.port }}
              scheme: HTTP
              httpHeaders:
                - name: "checkType"
                  value: "readinessProbe"
            initialDelaySeconds: 5
            periodSeconds: {{ .Values.templateAgent.healthChecking.readinessProbe.periodSeconds }}
            successThreshold: 1
            failureThreshold: {{ .Values.templateAgent.healthChecking.readinessProbe.failureThreshold }}
            timeoutSeconds: 5
          {{- with .Values.templateAgent.resources }}
          resources:
          {{- toYaml . | trim | nindent 12 }}
          {{- end }}
          env:
            - name: ENV_LOG_LEVEL
              value: {{ .Values.templateAgent.debug.logLevel | quote }}
            - name: ENV_ENABLED_METRIC
              value: {{ .Values.templateAgent.prometheus.enabled | quote }}
            - name: ENV_METRIC_HTTP_PORT
              value: {{ .Values.templateAgent.prometheus.port | quote }}
            - name: ENV_HEALTH_PORT
              value: {{ .Values.templateAgent.httpPort | quote }}
            - name: ENV_GOPS_LISTEN_PORT
              value: {{ .Values.templateAgent.debug.gopsPort | quote }}
            {{- with .Values.templateAgent.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.templateAgent.securityContext }}
          securityContext:
          {{- toYaml . | nindent 10 }}
          {{- end }}
          volumeMounts:
            - name: config-path
              mountPath: /tmp/config-map
              readOnly: true
            {{- if .Values.templateAgent.extraVolumes }}
            {{- include "tplvalues.render" ( dict "value" .Values.templateAgent.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
      volumes:
        # To read the configuration from the config map
        - name: config-path
          configMap:
            defaultMode: 0400
            name: {{ .Values.global.configName }}
      {{- if .Values.templateAgent.extraVolumeMounts }}
      {{- include "tplvalues.render" ( dict "value" .Values.templateAgent.extraVolumeMounts "context" $ ) | nindent 6 }}
      {{- end }}
