{{- if .Values.rocktemplateAgent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rocktemplateAgent.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "project.rocktemplateAgent.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.commonAnnotations .Values.rocktemplateAgent.serviceAccount.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.rocktemplateAgent.serviceAccount.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.rocktemplateAgent.serviceAccount.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- end }}
---
{{- if .Values.rocktemplateController.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rocktemplateController.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "project.rocktemplateController.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.commonAnnotations .Values.rocktemplateController.serviceAccount.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.rocktemplateController.serviceAccount.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.rocktemplateController.serviceAccount.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- end }}
