// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/spidernet-io/rocktemplate/pkg/k8s/apis/rocktemplate.spidernet.io/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// MybookLister helps list Mybooks.
// All objects returned here must be treated as read-only.
type MybookLister interface {
	// List lists all Mybooks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.Mybook, err error)
	// Get retrieves the Mybook from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.Mybook, error)
	MybookListerExpansion
}

// mybookLister implements the MybookLister interface.
type mybookLister struct {
	listers.ResourceIndexer[*v1.Mybook]
}

// NewMybookLister returns a new MybookLister.
func NewMybookLister(indexer cache.Indexer) MybookLister {
	return &mybookLister{listers.New[*v1.Mybook](indexer, v1.Resource("mybook"))}
}
