apiVersion: v2
name: template
home: "https://spidernet-io.github.io/agent"
# application or library
type: application
# no need to modify this version , CI will auto update it with /VERSION
version: 0.1.0
# This field is informational, and has no impact on chart version calculations .
# Leaving it unquoted can lead to parsing issues in some cases
# no need to modify this version , CI will auto update it with /VERSION
appVersion: "0.1.0"
kubeVersion: ">= 1.16.0-0"
description: template
sources:
  - "https://github.com/spidernet-io/template"
keywords:
  - template
maintainers:
  - name: spidernet-io
    url: https://github.com/spidernet-io
