name: Build Image CI

on:
  # called by daily build and push image
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      # ====modify====
      - images/agent/**
      - images/controller/**

permissions: write-all

jobs:
  call-by:
    uses: ./.github/workflows/call-release-image.yaml
    with:
      ref: ${{ inputs.ref }}
      push: "false"
      race: "1"
    secrets: inherit
