name: Score Oss Fuzz

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'github project, like "spidernet-io/rocktemplate" '
        required: false

permissions: write-all

jobs:
  name: Check label set
  runs-on: ubuntu-latest
  steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20.0'

    - name: run
      run: |
        set -x
        REPO_NAME=${{ github.event.inputs.repo }}
        if [ -z "${REPO_NAME}" ]; then
            REPO_NAME=${{ github.repository }}
        fi
        REPO_NAME="github.com/${REPO_NAME}"
        echo "score for ${REPO_NAME}"
        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        criticality_score --depsdev-disable   ${REPO_NAME}
