name: test

on:
  workflow_dispatch:

permissions: write-all

jobs:
  get_ref:
    runs-on: ubuntu-latest
    steps:
      - name: Get Original Ref
        run: |
          exit 1

  result:
    runs-on: ubuntu-latest
    needs: [get_ref]
    steps:
      - name: result
        run: |
          echo ${{ needs.get_ref.result }}
